-- Boots Hyper Market - product seed data
-- Generated from src/data/products.ts by scripts/generate-seed.mjs.
-- Do not edit by hand; re-run the generator instead.
--
-- Run in the Supabase SQL Editor AFTER schema.sql.
-- Re-running is safe: existing rows are updated, not duplicated.
-- Note that stock is only set on first insert, so re-seeding will not
-- overwrite stock levels you have since adjusted.

insert into public.products (
  name, slug, description, price, compare_at_price, images, sizes,
  category, brand, stock, is_active,
  department, gender, colors, material, care, featured
) values
  ('Classic Leather Boot', 'classic-leather-boot', 'A full-grain leather lace-up built on a Goodyear welt, finished with a cushioned footbed for all-day wear.', 2999, NULL, ARRAY['/images/products/classic-leather-boot-1.jpg', '/images/products/classic-leather-boot-2.jpg']::text[], ARRAY['6', '7', '8', '9', '10', '11']::text[], 'boots', 'Boots Hyper Market', 25, true, 'footwear', 'men', '[{"name":"Dark Brown","hex":"#4A3728"},{"name":"Black","hex":"#12110F"}]'::jsonb, 'Full-grain leather upper, leather lining, rubber outsole', 'Wipe with a damp cloth, condition with leather cream every few months, air dry away from direct heat.', true),
  ('Urban Chelsea Boot', 'urban-chelsea-boot', 'A clean-lined Chelsea with twin elastic gussets and a low stacked heel — easy to pull on, easy to wear.', 3499, NULL, ARRAY['/images/products/urban-chelsea-boot-1.jpg', '/images/products/urban-chelsea-boot-2.jpg']::text[], ARRAY['6', '7', '8', '9', '10', '11']::text[], 'boots', 'Boots Hyper Market', 25, true, 'footwear', 'unisex', '[{"name":"Black","hex":"#12110F"},{"name":"Tan","hex":"#A3764A"}]'::jsonb, 'Smooth calf leather upper, elastic side panels, rubber outsole', 'Brush off dust after wear. Use a neutral polish to restore shine. Avoid soaking the elastic panels.', false),
  ('Rugged Work Boot', 'rugged-work-boot', 'Built for long days on site. Reinforced stitching, a padded collar and a deep-lug outsole for grip.', 3999, NULL, ARRAY['/images/products/rugged-work-boot-1.jpg', '/images/products/rugged-work-boot-2.jpg']::text[], ARRAY['6', '7', '8', '9', '10', '11']::text[], 'boots', 'Boots Hyper Market', 25, true, 'footwear', 'men', '[{"name":"Wheat","hex":"#C2A171"},{"name":"Dark Brown","hex":"#4A3728"}]'::jsonb, 'Oiled nubuck upper, padded collar, slip-resistant rubber outsole', 'Remove mud before it dries. Re-oil the nubuck seasonally to keep it water resistant.', false),
  ('Everyday Ankle Boot', 'everyday-ankle-boot', 'A neat ankle silhouette with a side zip and a block heel that stays comfortable from morning to evening.', 2799, NULL, ARRAY['/images/products/everyday-ankle-boot-1.jpg', '/images/products/everyday-ankle-boot-2.jpg']::text[], ARRAY['6', '7', '8', '9', '10', '11']::text[], 'boots', 'Boots Hyper Market', 25, true, 'footwear', 'women', '[{"name":"Black","hex":"#12110F"},{"name":"Cream","hex":"#E8DFD2"}]'::jsonb, 'Soft leather upper, textile lining, 35mm block heel', 'Store upright with a boot shaper. Clean with a soft cloth and leather conditioner.', true),
  ('Heritage Lace-Up Boot', 'heritage-lace-up-boot', 'Brogue detailing over a classic derby last. A dress boot that holds its shape season after season.', 4299, NULL, ARRAY['/images/products/heritage-lace-up-boot-1.jpg', '/images/products/heritage-lace-up-boot-2.jpg']::text[], ARRAY['6', '7', '8', '9', '10', '11']::text[], 'boots', 'Boots Hyper Market', 25, true, 'footwear', 'men', '[{"name":"Cognac","hex":"#8E5A2B"},{"name":"Black","hex":"#12110F"}]'::jsonb, 'Burnished calf leather, leather insole, stacked leather heel', 'Use shoe trees between wears. Polish regularly and resole when the tread wears through.', false),
  ('Trail Hiking Boot', 'trail-hiking-boot', 'A mid-cut trail boot with ankle support, a moisture-wicking lining and a grip outsole for uneven ground.', 4599, NULL, ARRAY['/images/products/trail-hiking-boot-1.jpg', '/images/products/trail-hiking-boot-2.jpg']::text[], ARRAY['6', '7', '8', '9', '10', '11']::text[], 'boots', 'Boots Hyper Market', 25, true, 'footwear', 'unisex', '[{"name":"Olive","hex":"#5A5B3C"},{"name":"Charcoal","hex":"#3A3A38"}]'::jsonb, 'Nubuck and textile upper, moisture-wicking lining, multi-directional lug outsole', 'Rinse off grit after hikes, loosen the laces and let them dry fully before storing.', false),
  ('Suede Chelsea Boot', 'suede-chelsea-boot', 'Soft suede with a slim profile and a pull tab at the heel. Light enough for everyday, smart enough for evenings.', 3299, NULL, ARRAY['/images/products/suede-chelsea-boot-1.jpg', '/images/products/suede-chelsea-boot-2.jpg']::text[], ARRAY['6', '7', '8', '9', '10', '11']::text[], 'boots', 'Boots Hyper Market', 25, true, 'footwear', 'women', '[{"name":"Sand","hex":"#CDB79A"},{"name":"Grey","hex":"#8C857B"}]'::jsonb, 'Suede upper, elastic side panels, lightweight rubber sole', 'Use a suede brush to lift the nap and a protector spray before first wear.', false),
  ('Steel Toe Site Boot', 'steel-toe-site-boot', 'Safety-rated protection with a steel toe cap, oil-resistant sole and a shank that supports the arch.', 4999, NULL, ARRAY['/images/products/steel-toe-site-boot-1.jpg', '/images/products/steel-toe-site-boot-2.jpg']::text[], ARRAY['6', '7', '8', '9', '10', '11']::text[], 'boots', 'Boots Hyper Market', 25, true, 'footwear', 'men', '[{"name":"Black","hex":"#12110F"},{"name":"Dark Brown","hex":"#4A3728"}]'::jsonb, 'Water-resistant leather, steel toe cap, oil-resistant rubber outsole', 'Clean after each shift and check the laces and eyelets regularly for wear.', false),
  ('Minimal Desert Boot', 'minimal-desert-boot', 'Two-eyelet desert boot on a soft crepe sole. Pared back, lightweight and easy to pack.', 2499, NULL, ARRAY['/images/products/minimal-desert-boot-1.jpg', '/images/products/minimal-desert-boot-2.jpg']::text[], ARRAY['6', '7', '8', '9', '10', '11']::text[], 'boots', 'Boots Hyper Market', 25, true, 'footwear', 'unisex', '[{"name":"Sand","hex":"#CDB79A"},{"name":"Chocolate","hex":"#5C3D25"}]'::jsonb, 'Suede upper, unlined interior, natural crepe sole', 'Keep away from standing water. Brush the suede in one direction to keep the nap even.', false),
  ('Winter Lined Boot', 'winter-lined-boot', 'A taller shaft with a warm brushed lining and a sealed seam construction for cold, wet mornings.', 3899, NULL, ARRAY['/images/products/winter-lined-boot-1.jpg', '/images/products/winter-lined-boot-2.jpg']::text[], ARRAY['6', '7', '8', '9', '10', '11']::text[], 'boots', 'Boots Hyper Market', 25, true, 'footwear', 'women', '[{"name":"Black","hex":"#12110F"},{"name":"Taupe","hex":"#9C8A77"}]'::jsonb, 'Leather upper, brushed warm lining, sealed seams, grip outsole', 'Dry naturally at room temperature. Treat with a water repellent before winter.', false),
  ('Field Combat Boot', 'field-combat-boot', 'Speed hooks, a reinforced toe and a broad outsole. A sturdy everyday boot with a utility edge.', 3699, NULL, ARRAY['/images/products/field-combat-boot-1.jpg', '/images/products/field-combat-boot-2.jpg']::text[], ARRAY['6', '7', '8', '9', '10', '11']::text[], 'boots', 'Boots Hyper Market', 25, true, 'footwear', 'unisex', '[{"name":"Black","hex":"#12110F"},{"name":"Olive","hex":"#5A5B3C"}]'::jsonb, 'Leather and canvas upper, speed-hook lacing, cushioned rubber outsole', 'Wipe clean, then condition the leather panels. Replace the laces as they fray.', false),
  ('Alpine Trek Boot', 'alpine-trek-boot', 'Our most supportive boot. A stiffer midsole and high-abrasion heel for long distances and heavy loads.', 5299, NULL, ARRAY['/images/products/alpine-trek-boot-1.jpg', '/images/products/alpine-trek-boot-2.jpg']::text[], ARRAY['6', '7', '8', '9', '10', '11']::text[], 'boots', 'Boots Hyper Market', 25, true, 'footwear', 'men', '[{"name":"Brown","hex":"#6B4A2F"},{"name":"Black","hex":"#12110F"}]'::jsonb, 'Full-grain leather upper, stiffened midsole, high-abrasion rubber outsole', 'Clean the welt after use and store in a dry place with the laces loosened.', false),
  ('Court Sneaker', 'court-sneaker', 'A clean white court shoe on a cupsole. Minimal branding, easy to keep smart and goes with everything.', 1899, NULL, ARRAY['/images/products/court-sneaker-1.jpg', '/images/products/court-sneaker-2.jpg']::text[], ARRAY['6', '7', '8', '9', '10', '11']::text[], 'sneakers', 'Boots Hyper Market', 25, true, 'footwear', 'unisex', '[{"name":"White","hex":"#F2F0EC"},{"name":"Black","hex":"#12110F"}]'::jsonb, 'Leather upper, textile lining, vulcanised rubber cupsole', 'Wipe with a damp cloth and mild soap. Air dry; do not machine wash.', true),
  ('Air Runner Sneaker', 'air-runner-sneaker', 'A cushioned everyday running silhouette with a breathable mesh upper and a lightweight foam midsole.', 2499, NULL, ARRAY['/images/products/air-runner-sneaker-1.jpg', '/images/products/air-runner-sneaker-2.jpg']::text[], ARRAY['6', '7', '8', '9', '10', '11']::text[], 'sneakers', 'Boots Hyper Market', 25, true, 'footwear', 'unisex', '[{"name":"White / Orange","hex":"#E4855A"},{"name":"Grey","hex":"#8C857B"}]'::jsonb, 'Engineered mesh upper, foam midsole, rubber outsole', 'Remove the insoles and laces before cleaning. Air dry away from direct sun.', false),
  ('Oxford Brogue Shoe', 'oxford-brogue-shoe', 'A closed-lacing Oxford with full brogue punching. The formal shoe to keep for weddings and work.', 2799, NULL, ARRAY['/images/products/oxford-brogue-shoe-1.jpg', '/images/products/oxford-brogue-shoe-2.jpg']::text[], ARRAY['6', '7', '8', '9', '10', '11']::text[], 'formal', 'Boots Hyper Market', 25, true, 'footwear', 'men', '[{"name":"Cognac","hex":"#8E5A2B"},{"name":"Black","hex":"#12110F"}]'::jsonb, 'Polished calf leather, leather sole, leather lining', 'Use shoe trees, polish before each wear and rotate pairs to let the leather rest.', true),
  ('Derby Formal Shoe', 'derby-formal-shoe', 'Open lacing gives a roomier fit than an Oxford, so it suits a wider foot without losing the smart line.', 2399, NULL, ARRAY['/images/products/derby-formal-shoe-1.jpg', '/images/products/derby-formal-shoe-2.jpg']::text[], ARRAY['6', '7', '8', '9', '10', '11']::text[], 'formal', 'Boots Hyper Market', 25, true, 'footwear', 'men', '[{"name":"Black","hex":"#12110F"},{"name":"Dark Brown","hex":"#4A3728"}]'::jsonb, 'Calf leather upper, leather lining, stacked heel', 'Condition every few months and keep away from prolonged damp.', false),
  ('Comfort Slide Sandal', 'comfort-slide-sandal', 'A contoured footbed that moulds to the foot, with adjustable buckle straps for an exact fit.', 899, NULL, ARRAY['/images/products/comfort-slide-sandal-1.jpg', '/images/products/comfort-slide-sandal-2.jpg']::text[], ARRAY['6', '7', '8', '9', '10', '11']::text[], 'sandals', 'Boots Hyper Market', 25, true, 'footwear', 'unisex', '[{"name":"Tan","hex":"#A3764A"},{"name":"Black","hex":"#12110F"}]'::jsonb, 'Leather straps, cork and latex footbed, EVA outsole', 'Keep the footbed dry. Brush off sand and wipe the straps with a damp cloth.', false),
  ('Summer Strap Sandal', 'summer-strap-sandal', 'A low platform sandal with soft leather straps — dressy enough for evenings, easy enough for every day.', 1199, NULL, ARRAY['/images/products/summer-strap-sandal-1.jpg', '/images/products/summer-strap-sandal-2.jpg']::text[], ARRAY['6', '7', '8', '9', '10', '11']::text[], 'sandals', 'Boots Hyper Market', 25, true, 'footwear', 'women', '[{"name":"Maroon","hex":"#5C1014"},{"name":"Tan","hex":"#A3764A"}]'::jsonb, 'Leather upper, padded insole, lightweight platform sole', 'Store away from direct heat so the straps keep their shape.', false),
  ('Everyday Laptop Backpack', 'everyday-laptop-backpack', 'A padded 15" laptop sleeve, water-resistant shell and enough organisation for a full day out.', 1999, NULL, ARRAY['/images/products/everyday-laptop-backpack-1.jpg', '/images/products/everyday-laptop-backpack-2.jpg']::text[], ARRAY['One Size']::text[], 'backpacks', 'Boots Hyper Market', 25, true, 'bags', 'unisex', '[{"name":"Navy","hex":"#26324A"},{"name":"Black","hex":"#12110F"}]'::jsonb, 'Water-resistant polyester, padded laptop sleeve, YKK zips', 'Spot clean with mild soap and water. Do not tumble dry.', true),
  ('Canvas Trek Backpack', 'canvas-trek-backpack', 'Waxed canvas and leather trim over a roomy 30-litre main compartment. Made for weekends away.', 2499, NULL, ARRAY['/images/products/canvas-trek-backpack-1.jpg', '/images/products/canvas-trek-backpack-2.jpg']::text[], ARRAY['One Size']::text[], 'backpacks', 'Boots Hyper Market', 25, true, 'bags', 'unisex', '[{"name":"Dark Brown","hex":"#4A3728"},{"name":"Olive","hex":"#5A5B3C"}]'::jsonb, 'Waxed canvas body, full-grain leather trim, brass hardware', 'Re-wax the canvas once a year. Wipe the leather with a barely damp cloth.', false),
  ('Woven Leather Tote', 'woven-leather-tote', 'A soft woven tote that holds its shape, with a lined interior and a zip pocket for essentials.', 2899, NULL, ARRAY['/images/products/woven-leather-tote-1.jpg', '/images/products/woven-leather-tote-2.jpg']::text[], ARRAY['One Size']::text[], 'handbags', 'Boots Hyper Market', 25, true, 'bags', 'women', '[{"name":"Tan","hex":"#A3764A"},{"name":"Black","hex":"#12110F"}]'::jsonb, 'Woven leather, cotton lining, magnetic closure', 'Store stuffed to keep the weave even. Keep away from prolonged damp.', false),
  ('Structured Satchel', 'structured-satchel', 'A firm-sided satchel with buckle straps and a detachable shoulder strap for carrying two ways.', 3299, NULL, ARRAY['/images/products/structured-satchel-1.jpg', '/images/products/structured-satchel-2.jpg']::text[], ARRAY['One Size']::text[], 'handbags', 'Boots Hyper Market', 25, true, 'bags', 'women', '[{"name":"Grey","hex":"#8C857B"},{"name":"Maroon","hex":"#5C1014"}]'::jsonb, 'Structured leather, gold-tone hardware, detachable strap', 'Wipe with a soft dry cloth and store in the dust bag provided.', false),
  ('Top Handle Handbag', 'top-handle-handbag', 'A compact top-handle bag in smooth leather. Neat enough for occasions, roomy enough for daily use.', 2599, NULL, ARRAY['/images/products/top-handle-handbag-1.jpg', '/images/products/top-handle-handbag-2.jpg']::text[], ARRAY['One Size']::text[], 'handbags', 'Boots Hyper Market', 25, true, 'bags', 'women', '[{"name":"Dark Brown","hex":"#4A3728"},{"name":"Cream","hex":"#E8DFD2"}]'::jsonb, 'Smooth leather, fabric lining, flap closure', 'Avoid overfilling so the frame keeps its shape.', true),
  ('Leather Duffel Bag', 'leather-duffel-bag', 'A cabin-friendly weekender in thick leather, with a wide opening and a padded shoulder strap.', 3999, NULL, ARRAY['/images/products/leather-duffel-bag-1.jpg', '/images/products/leather-duffel-bag-2.jpg']::text[], ARRAY['One Size']::text[], 'duffels', 'Boots Hyper Market', 25, true, 'bags', 'unisex', '[{"name":"Dark Brown","hex":"#4A3728"},{"name":"Black","hex":"#12110F"}]'::jsonb, 'Thick full-grain leather, cotton twill lining, metal feet', 'Condition twice a year. The leather will darken and soften with use.', false),
  ('Cabin Trolley 55cm', 'cabin-trolley-55', 'Fits most cabin size limits. Four spinner wheels, a TSA lock and a split interior with tie-down straps.', 4499, NULL, ARRAY['/images/products/cabin-trolley-55-1.jpg', '/images/products/cabin-trolley-55-2.jpg']::text[], ARRAY['55 cm']::text[], 'cabin', 'Boots Hyper Market', 25, true, 'trolleys', 'unisex', '[{"name":"Navy","hex":"#26324A"},{"name":"Cream","hex":"#E8DFD2"}]'::jsonb, 'Polypropylene hard shell, aluminium handle, dual spinner wheels', 'Wipe the shell with a damp cloth. Check wheel screws occasionally.', true),
  ('Check-In Trolley 65cm', 'check-in-trolley-65', 'A medium check-in case with an expander zip for the return leg, and a fully lined split interior.', 5499, NULL, ARRAY['/images/products/check-in-trolley-65-1.jpg', '/images/products/check-in-trolley-65-2.jpg']::text[], ARRAY['65 cm', '75 cm']::text[], 'checkin', 'Boots Hyper Market', 25, true, 'trolleys', 'unisex', '[{"name":"Graphite","hex":"#4A4D52"},{"name":"Maroon","hex":"#5C1014"}]'::jsonb, 'Ribbed hard shell, expander zip, TSA combination lock', 'Do not overfill past the expander. Clean scuffs with a soft cloth.', false),
  ('Aluminium Hard Trolley', 'aluminium-hard-trolley', 'A full aluminium shell with recessed latches. Heavier than plastic, and far better at taking a knock.', 7999, NULL, ARRAY['/images/products/aluminium-hard-trolley-1.jpg', '/images/products/aluminium-hard-trolley-2.jpg']::text[], ARRAY['55 cm', '65 cm']::text[], 'cabin', 'Boots Hyper Market', 25, true, 'trolleys', 'unisex', '[{"name":"Silver","hex":"#B9BCC0"},{"name":"Graphite","hex":"#4A4D52"}]'::jsonb, 'Anodised aluminium shell, recessed latches, silent spinner wheels', 'Scratches are normal and part of the finish. Keep the latches free of grit.', false),
  ('Business Trolley 45cm', 'business-trolley-45', 'An underseat case with a front laptop compartment, so the essentials stay reachable in transit.', 4999, NULL, ARRAY['/images/products/business-trolley-45-1.jpg', '/images/products/business-trolley-45-2.jpg']::text[], ARRAY['45 cm']::text[], 'cabin', 'Boots Hyper Market', 25, true, 'trolleys', 'unisex', '[{"name":"Maroon","hex":"#5C1014"},{"name":"Black","hex":"#12110F"}]'::jsonb, 'Hard shell with front-opening laptop pocket, USB pass-through', 'Keep the front pocket clear of sharp items to protect the laptop panel.', false),
  ('3-Piece Trolley Set', 'trolley-set-3piece', 'Cabin, medium and large in one matching set, each nesting inside the next for easy storage.', 9999, NULL, ARRAY['/images/products/trolley-set-3piece-1.jpg', '/images/products/trolley-set-3piece-2.jpg']::text[], ARRAY['55 + 65 + 75 cm']::text[], 'sets', 'Boots Hyper Market', 25, true, 'trolleys', 'unisex', '[{"name":"Navy","hex":"#26324A"},{"name":"Maroon","hex":"#5C1014"}]'::jsonb, 'Polypropylene shells, aluminium handles, TSA locks on all three', 'Nest the cases for storage. Clean each shell with a damp cloth.', true)
on conflict (slug) do update set
  name        = excluded.name,
  description = excluded.description,
  price       = excluded.price,
  images      = excluded.images,
  sizes       = excluded.sizes,
  category    = excluded.category,
  department  = excluded.department,
  gender      = excluded.gender,
  colors      = excluded.colors,
  material    = excluded.material,
  care        = excluded.care,
  featured    = excluded.featured,
  updated_at  = now();
